#!/bin/bash

# Coffeeverse Azure Deployment Script
# Deploys the complete Azure ETL infrastructure using Bicep templates

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
PROJECT_NAME="coffeeverse"
ENVIRONMENT="dev"
LOCATION="eastus"
TEMPLATE_FILE="main.bicep"
DEPLOYMENT_NAME="${PROJECT_NAME}-deployment-$(date +%Y%m%d-%H%M%S)"

# Functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_prerequisites() {
    log_info "Checking prerequisites..."

    # Check if Azure CLI is installed
    if ! command -v az &> /dev/null; then
        log_error "Azure CLI is not installed. Please install it from: https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
        exit 1
    fi

    # Check if Bicep CLI is installed
    if ! command -v bicep &> /dev/null; then
        log_warning "Bicep CLI not found. Installing..."
        az bicep install
    fi

    # Check if logged in to Azure
    if ! az account show &> /dev/null; then
        log_error "Not logged in to Azure. Please run: az login"
        exit 1
    fi

    log_success "Prerequisites check passed"
}

create_resource_group() {
    local rg_name="${PROJECT_NAME}-rg-${ENVIRONMENT}"

    log_info "Creating resource group: $rg_name in $LOCATION"

    if az group show --name "$rg_name" &> /dev/null; then
        log_warning "Resource group $rg_name already exists"
    else
        az group create \
            --name "$rg_name" \
            --location "$LOCATION" \
            --tags Project="$PROJECT_NAME" Environment="$ENVIRONMENT" \
            --output none
        log_success "Resource group created"
    fi

    echo "$rg_name"
}

deploy_infrastructure() {
    local rg_name="$1"
    local template_path="$TEMPLATE_FILE"

    log_info "Deploying infrastructure with Bicep template: $template_path"
    log_info "Deployment name: $DEPLOYMENT_NAME"

    # Validate template first
    log_info "Validating Bicep template..."
    az deployment group validate \
        --resource-group "$rg_name" \
        --template-file "$template_path" \
        --parameters environment="$ENVIRONMENT" projectName="$PROJECT_NAME" \
        --output none

    log_success "Template validation passed"

    # Deploy
    log_info "Starting deployment..."
    az deployment group create \
        --resource-group "$rg_name" \
        --template-file "$template_path" \
        --parameters environment="$ENVIRONMENT" projectName="$PROJECT_NAME" \
        --name "$DEPLOYMENT_NAME" \
        --output none

    log_success "Infrastructure deployment completed"
}

get_deployment_outputs() {
    local rg_name="$1"

    log_info "Getting deployment outputs..."

    # Get outputs and save to environment file
    local output_file=".env.azure"

    az deployment group show \
        --resource-group "$rg_name" \
        --name "$DEPLOYMENT_NAME" \
        --query "properties.outputs" \
        --output json > deployment_outputs.json

    # Extract key values
    local storage_account=$(jq -r '.storageAccountName.value' deployment_outputs.json)
    local storage_key=$(jq -r '.storageAccountKey.value' deployment_outputs.json)
    local cosmos_endpoint=$(jq -r '.cosmosAccountEndpoint.value' deployment_outputs.json)
    local cosmos_key=$(jq -r '.cosmosAccountKey.value' deployment_outputs.json)
    local function_app=$(jq -r '.functionAppName.value' deployment_outputs.json)

    # Create .env file for local development
    cat > "$output_file" << EOF
# Azure Configuration - Generated by deployment script
# DO NOT commit this file to version control

AZURE_STORAGE_ACCOUNT=$storage_account
AZURE_STORAGE_KEY=$storage_key
AZURE_COSMOS_URL=$cosmos_endpoint
AZURE_COSMOS_KEY=$cosmos_key
AZURE_FUNCTION_APP=$function_app
AZURE_RESOURCE_GROUP=$rg_name
AZURE_LOCATION=$LOCATION

# Streamlit secrets (copy these to Streamlit Cloud)
# AZURE_STORAGE_ACCOUNT=$storage_account
# AZURE_STORAGE_KEY=$storage_key
# AZURE_COSMOS_URL=$cosmos_endpoint
# AZURE_COSMOS_KEY=$cosmos_key
EOF

    log_success "Environment configuration saved to: $output_file"
    log_warning "⚠️  Remember to add the .env.azure file to .gitignore!"
}

deploy_function_app() {
    local function_app_name="$1"
    local rg_name="$2"

    log_info "Deploying Azure Function code..."

    # Check if function app code exists
    if [ ! -d "../azure_function" ]; then
        log_error "Azure Function code not found in ../azure_function"
        return 1
    fi

    # Create deployment package
    cd ../azure_function
    zip -r function_app.zip . -x "*.git*" "*.env*" "*.log*"

    # Deploy to Azure Functions
    az functionapp deployment source config-zip \
        --resource-group "$rg_name" \
        --name "$function_app_name" \
        --src function_app.zip \
        --output none

    # Clean up
    rm function_app.zip
    cd ../deploy

    log_success "Azure Function deployed"
}

main() {
    echo "🚀 Coffeeverse Azure Infrastructure Deployment"
    echo "=============================================="
    echo

    check_prerequisites

    local rg_name
    rg_name=$(create_resource_group)

    deploy_infrastructure "$rg_name"

    get_deployment_outputs "$rg_name"

    # Get function app name from outputs
    local function_app_name=$(jq -r '.functionAppName.value' deployment_outputs.json)
    deploy_function_app "$function_app_name" "$rg_name"

    echo
    log_success "🎉 Deployment completed successfully!"
    echo
    echo "Next steps:"
    echo "1. Copy Streamlit secrets from .env.azure to Streamlit Cloud"
    echo "2. Test the Azure Function: curl https://$function_app_name.azurewebsites.net/api/health"
    echo "3. Deploy Streamlit app to Streamlit Cloud"
    echo "4. Load sample data and test the ETL pipeline"
    echo
    echo "For cleanup, run: ./destroy.sh"
}

# Cleanup function
cleanup() {
    if [ -f "deployment_outputs.json" ]; then
        rm deployment_outputs.json
        log_info "Cleaned up temporary files"
    fi
}

# Trap for cleanup
trap cleanup EXIT

# Run main function
main "$@"
